apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xds-api-test
  namespace: istio-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: xds-api-test
        version: v1
    spec:
      containers:
      - name: xds-api-test
        image: go-chassis/xds-api-test:v1
        imagePullPolicy: IfNotPresent
        args: ["istio-pilot.istio-system:15010"]
---

